services:
  dmv-app:
    # platform: linux/amd64
    build:
      context: .
      dockerfile: ./dmv-app/Dockerfile
    image: dmv-app
    ports:
      - "8090:3000"
    volumes:
      - ./dmv-app:/app
      - /app/node_modules
      - ./dc-agency/docker/ca-bundle.pem:/certs/ca-bundle.pem:ro
    environment:
      - CUSTOM_CA_PATH=/certs/ca-bundle.pem
      - NODE_EXTRA_CA_CERTS=/certs/ca-bundle.pem
    env_file:
      - ./.env
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - dmv-network
      - iviadc-demo

  bank-app:
    # platform: linux/amd64
    build:
      context: .
      dockerfile: ./bank-app/Dockerfile
    image: bank-app
    ports:
      - "8091:3000"
    volumes:
      - ./bank-app:/app
      - /app/node_modules
      - ./dc-agency/docker/ca-bundle.pem:/certs/ca-bundle.pem:ro
    environment:
      - CUSTOM_CA_PATH=/certs/ca-bundle.pem
      - NODE_EXTRA_CA_CERTS=/certs/ca-bundle.pem
    env_file:
      - ./.env
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - bank-network
      - iviadc-demo

networks:
  dmv-network:
    name: dmv-network
  bank-network:
    name: bank-network
  iviadc-demo:
    name: iviadc-demo
    external: true

# Made with Bob
