apiVersion: v1
kind: ConfigMap
metadata:
  name: oid4vc-config
data:
  ACCOUNT_URL: ""
  REACT_APP_ACCOUNT_URL: ""
  TOKEN_ENDPOINT: ""
  DMV_AGENT_NAME: "DMVIssuer"
  DMV_AGENT_ID: ""
  REACT_APP_DMV_AGENT_ID: ""
  REACT_APP_CLIENT_ID: ""
  REACT_APP_CLIENT_SECRET: ""
  DMV_AGENT_PASSWORD: ""
  REACT_APP_DMV_AGENT_PASSWORD: ""
  BANK_AGENT_NAME: "BankVerifier"
  BANK_AGENT_ID: ""
  REACT_APP_BANK_AGENT_ID: ""
  BANK_AGENT_PASSWORD: ""
  REACT_APP_BANK_AGENT_PASSWORD: ""
  CREDENTIAL_SCHEMA_ID: ""
  REACT_APP_CREDENTIAL_SCHEMA_ID: ""
  CREDENTIAL_DEFINITION_ID: ""
  REACT_APP_CREDENTIAL_DEFINITION_ID: ""
  EXCHANGE_TEMPLATE_ID: ""
  REACT_APP_EXCHANGE_TEMPLATE_ID: ""
  W3_ROOT: ""
  REACT_APP_W3_ROOT: ""

# Made with Bob
